### PR TITLE
Update .drone.star for 'drop PHP 7.2 support'

### PR DESCRIPTION
**Pull request by phil-davis**
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687

### CODE REVIEW

**Review by individual-it — COMMENTED** [review]
looks like phan needs some extra love

**Comment by phil-davis** [comment]
I have given it love by suppressing the `PhanDeprecatedClass` messages. There are quite a few `phan-suppress-next-line` in the code. I raised issue #232 for someone (tm) to look at those.

**Comment by phil-davis** [comment]
@individual-it @dpakach ready for review again.

**Review by dpakach — COMMENTED** [review]
lgtm 👍🏼

**Review by individual-it — APPROVED** [review]
do we need a new release because of the changed `min-version`?

**Comment by phil-davis** [comment]
> do we need a new release because of the changed min-version?

There is a release in progress at the moment #220 - I will ping there before merging this. Maybe they can get the release done first, so that it can work with ownCloud core 10.8.0 + PHP 7.2 combination.

**Comment by phil-davis** [comment]
I changed this to "draft" - https://github.com/owncloud/search_elastic/issues/220#issuecomment-912477219 needs to be sorted out for the upcoming release first.

**Comment by phil-davis** [comment]
https://github.com/owncloud/search_elastic/issues/220#issuecomment-912484937

Merging

**Pull request merged**
